# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x08protobuf\x1a\x1bgoogle/protobuf/empty.proto\"[\n\x10ShowShotsRequest\x12(\n\ntableState\x18\x01 \x02(\x0b\x32\x14.protobuf.TableState\x12\x1d\n\x05shots\x18\x02 \x03(\x0b\x32\x0e.protobuf.Shot\"+\n\nTableState\x12\x1d\n\x05\x62\x61lls\x18\x01 \x03(\x0b\x32\x0e.protobuf.Ball\"C\n\x04\x42\x61ll\x12\x1c\n\x03pos\x18\x01 \x02(\x0b\x32\x0f.protobuf.Point\x12\x0e\n\x06number\x18\x02 \x02(\x05\x12\r\n\x05state\x18\x03 \x02(\x05\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\"\x89\x02\n\x04Shot\x12 \n\x04type\x18\x01 \x02(\x0e\x32\x12.protobuf.ShotType\x12\x1c\n\x04next\x18\x02 \x01(\x0b\x32\x0e.protobuf.Shot\x12\x1e\n\x06\x62ranch\x18\x03 \x01(\x0b\x32\x0e.protobuf.Shot\x12\x1e\n\x05posB1\x18\x04 \x01(\x0b\x32\x0f.protobuf.Point\x12\"\n\tghostBall\x18\x05 \x01(\x0b\x32\x0f.protobuf.Point\x12!\n\x08leftMost\x18\x06 \x01(\x0b\x32\x0f.protobuf.Point\x12\"\n\trightMost\x18\x07 \x01(\x0b\x32\x0f.protobuf.Point\x12\n\n\x02\x62\x31\x18\x08 \x01(\x05\x12\n\n\x02\x62\x32\x18\t \x01(\x05*U\n\x08ShotType\x12\x0e\n\nCUE_STRIKE\x10\x00\x12\n\n\x06POCKET\x10\x01\x12\x08\n\x04RAIL\x10\x02\x12\n\n\x06STRIKE\x10\x03\x12\x08\n\x04KISS\x10\x04\x12\r\n\tBALL_BOTH\x10\x05\x32M\n\x08JPoolAPI\x12\x41\n\tShowShots\x12\x1a.protobuf.ShowShotsRequest\x1a\x16.google.protobuf.Empty\"\x00\x42!\n\x12org.JPool.protobufB\tApiProtosP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022org.JPool.protobufB\tApiProtosP\001'
  _globals['_SHOTTYPE']._serialized_start=558
  _globals['_SHOTTYPE']._serialized_end=643
  _globals['_SHOWSHOTSREQUEST']._serialized_start=52
  _globals['_SHOWSHOTSREQUEST']._serialized_end=143
  _globals['_TABLESTATE']._serialized_start=145
  _globals['_TABLESTATE']._serialized_end=188
  _globals['_BALL']._serialized_start=190
  _globals['_BALL']._serialized_end=257
  _globals['_POINT']._serialized_start=259
  _globals['_POINT']._serialized_end=288
  _globals['_SHOT']._serialized_start=291
  _globals['_SHOT']._serialized_end=556
  _globals['_JPOOLAPI']._serialized_start=645
  _globals['_JPOOLAPI']._serialized_end=722
# @@protoc_insertion_point(module_scope)
